### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by tvinke** [donbeave/graphql-java-datetime#1]
Kudos for the hard work!

Unfortunately, I can not find the dependency `com.graphql-java:graphql-datetime-spring-boot-starter:2017-07-15T18-08-56` online.

I can not resolve it through [Maven Central](https://mvnrepository.com/artifact/com.graphql-java) or JCenter.

I can of course get it from your GitHub repo, but could you publish it to a repository?

**Comment by donbeave** [comment]
Hi @tvinke !

I will do it.

Temporary you can use this maven repo: https://dl.bintray.com/donbeave/maven/

Best regards,
  Alexey Zhokhov.

**Comment by donbeave** [comment]
@tvinke 
Please you this dependency `com.zhokhov.graphql:graphql-datetime-spring-boot-starter:1.0.0`. I need to change package for Maven publication.

**Comment by donbeave** [comment]
@tvinke available in `jcenter` already:
https://bintray.com/bintray/jcenter?filterByPkgName=graphql-java-datetime

**Comment by tvinke** [comment]
Hi Alexey, thank you. 

My weekend starts now, but I'll give it a go early next week!

Regards, Ted

**Comment by BAVhel** [comment]
please add also in maven central

**Comment by DenisBogatirov** [comment]
Is it on maven central already?

**Comment by donbeave** [comment]
Done. 

@DenisBogatirov @tvinke @BAVhel guys, you can find the latest version on maven central repo:
http://search.maven.org/#artifactdetails%7Ccom.zhokhov.graphql%7Cgraphql-datetime-spring-boot-starter%7C1.1.0%7Cjar
