### ISSUE TITLE
Please upgrade graphql deps

### ISSUE THREAD

**Issue by mcbain** [donbeave/graphql-java-datetime#11]
The groupId was changed in the latest graphql libs.

<dependency>
      <groupId>com.graphql-java-kickstart</groupId>
      <artifactId>graphql-java-servlet</artifactId>
      <version>7.1.1</version>
</dependency>

**Comment by donbeave** [comment]
Done. Please use `1.4.0` version:
https://bintray.com/donbeave/maven/graphql-java-datetime/1.4.0

It will be available in Maven Central soon.
