### ISSUE TITLE
Zone conversion is not applied to LocalDate

### ISSUE THREAD

**Issue by oliemansm** [donbeave/graphql-java-datetime#14]
I ran into the issue that Apollo Client sends a `Date` for a `LocalDate` scalar with time included. Zone conversion is not applied by `GraphQLLocalDate` resulting in an incorrect date being parsed. Will create a PR to extend zone conversion support to the `GraphQLLocalDate` scalar. Will check `GraphQLLocalTime` while I'm at it too.

**Comment by donbeave** [comment]
@oliemansm thank you! I'll release it today.

**Comment by oliemansm** [comment]
Great, thanks!
