### ISSUE TITLE
Not working with webflux

### ISSUE THREAD

**Issue by darkrift** [donbeave/graphql-java-datetime#16]
Using the spring boot starter gives me the following error within a webflux environment : 

The bean 'requestMappingHandlerAdapter', defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/web/reactive/config/DelegatingWebFluxConfiguration.class] and overriding is disabled.

**Comment by donbeave** [comment]
Hi, @darkrift!

Can you make a small sample app to reproduce this error?

**Comment by PhilippS93** [comment]
The same problem with:

    compile group: 'com.graphql-java', name: 'graphql-spring-boot-starter', version: '5.0.2'
    compile group: 'com.graphql-java', name: 'graphql-java-tools', version: '5.2.4'

Result:

The bean 'serverEndpointRegistration', defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebsocketAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by Jam3si** [comment]
Same here:

The bean 'schemaStringProvider', defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class] and overriding is disabled.
Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by dayervi** [comment]
I made a pull request with a starting point to have scalars working with webflux #23.
It's a starter dependency issue. There must be a dedicate webflux starter with the right dependencies to make it work.

**Comment by donbeave** [comment]
@darkrift @Jam3si @PhilippS93 please check the latest version, it supports webflux now.

kudos to @dayervi
