### ISSUE TITLE
Change LocalDateTime format

### ISSUE THREAD

**Issue by asfernandes** [donbeave/graphql-java-datetime#18]
In README there is mentioned various formats.

But I don't see a way to actually change it.

I want to use `yyyy-MM-dd'T'HH:MM:ss` for `LocalDateTime` but can't see how to do.

The default format has a `Z` in the end that I want to remove.

**Comment by donbeave** [comment]
It's not changeable actually, but we support these formats when we parse LocalDateTime, but it looks like the documentation is wrong, seems `yyyy-MM-dd'T'HH:MM:ss` is not supported, only `yyyy-MM-dd'T'HH:MM:ssZ`, you can check this test: https://github.com/donbeave/graphql-java-datetime/blob/bda84ffb6c8f994a27950949bd5d7d884bab561f/graphql-java-datetime/src/test/groovy/com/zhokhov/graphql/datetime/GraphQLLocalDateTimeTest.groovy#L37

If it's ok you can make a PR.

**Comment by vlad-buzea-ullink** [comment]
Could you please add a config to specify the formats for LocalDate and LocalDateTime?

**Comment by donbeave** [comment]
@asfernandes @vlad-buzea-ullink I just check, actually, the current version support parsing `yyyy-MM-dd'T'HH:MM:ss` without `Z` in the end. It's working for the input format. Vlad if you need to specify the format for the output, yeah, this functionality is not implemented, but I'm open for PR, if you have time to improve it, please welcome!

**Comment by donbeave** [comment]
Fixed in this PR: https://github.com/donbeave/graphql-java-datetime/pull/25

**Comment by vlad-buzea-ullink** [comment]
> Fixed in this PR: #25

Actually my PR is only for `LocalDate`. `LocalDateTime ` is not done yet

**Comment by donbeave** [comment]
Done. Now it supports `LocalDateTime` also.
