### ISSUE TITLE
Use standard version of graphql java

### ISSUE THREAD

**Issue by TerryTran** [donbeave/graphql-java-datetime#2]
Could you switch to use the standard version of graphql-java: https://mvnrepository.com/artifact/com.graphql-java/graphql-java/3.0.0

**Comment by donbeave** [comment]
Hi, @TerryTran 

Not yet, my implementation using this class: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/CoercingSerializeException.java (it's available only on snapshot version).

Waiting for release of new `graphql-java`.
