### ISSUE TITLE
Update to graph kickstart 6

### ISSUE THREAD

**Issue by driverpt** [donbeave/graphql-java-datetime#21]
We've recently upgraded to 
```
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>6.0.0</version>
        </dependency>
```

And now we're getting errors:

```
Caused by: java.lang.ClassNotFoundException: com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration
```

I noticed that in `master` it's already been changed to the correct class name: https://github.com/donbeave/graphql-java-datetime/blob/master/graphql-datetime-autoconfigure/src/main/java/com/zhokhov/graphql/datetime/boot/GraphQLDateTimeAutoConfiguration.java#L29

When can this be released?

**Comment by donbeave** [comment]
Just released, a few minutes ago: https://bintray.com/donbeave/maven/graphql-java-datetime/1.6.0

It will be available in Maven Central soon.

**Comment by donbeave** [comment]
Available in Maven Central: https://search.maven.org/artifact/com.zhokhov.graphql/graphql-java-datetime/1.6.0/jar
