### ISSUE TITLE
bean 'schemaStringProvider' could not be registered

### ISSUE THREAD

**Issue by LeslieMurphy** [donbeave/graphql-java-datetime#24]
I am using graphql-spring-boot-starter 5.0.2 with graphql-java-tools 5.2.4.  

When I try to add graphql-datetime-spring-boot-starter 1.9.0 to use LocalDateTime in my schema, I get this error:

The bean 'schemaStringProvider', defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class] and overriding is disabled.

**Comment by donbeave** [comment]
@LeslieMurphy Thank you for reporting this issue. This is because this library is using the old version of `graphql-java-tools`. I'm fixing it, the fix will be available after 30 minutes.

**Comment by LeslieMurphy** [comment]
Thanks!  Is there a jar file or a way I can use Maven to plug the new version into my project and test it out?

**Comment by donbeave** [comment]
You have 3 options:
1) build it locally and publish to local maven 
2) use Bintray (https://bintray.com/beta/#/donbeave/maven/graphql-java-datetime)
3) wait until it will be synced to Maven (https://travis-ci.org/github/donbeave/graphql-java-datetime/builds/694761949), sometimes it takes a few hours

**Comment by LeslieMurphy** [comment]
I went with option 3 - used the Maven 2.0.0 version of graphql-datetime-spring-boot-starter and still get the same error.  is there any additional troubleshooting detail I can provide?

Invalid bean definition with name 'schemaStringProvider' defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=graphql.kickstart.tools.boot.GraphQLJavaToolsAutoConfiguration; factoryMethodName=schemaStringProvider; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class]] for bean 'schemaStringProvider': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration; factoryMethodName=schemaStringProvider; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]] bound.

The bean 'schemaStringProvider', defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class] and overriding is disabled.

**Comment by LeslieMurphy** [comment]
Update:  If I remove graphql-spring-boot-starter 5.0.2 and use graphql-datetime-spring-boot-starter 2.0.0 I do not get the conflict, and my app starts up.  However I do not get a /graphql endpoint when I do so.

**Comment by donbeave** [comment]
I think I know why because you are using the old version of `graphql-spring-boot-starter`. You need to upgrade to 7.0.1: https://search.maven.org/artifact/com.graphql-java-kickstart/graphql-spring-boot-starter/7.0.1/jar

**Comment by donbeave** [comment]
Seems you are using this version: https://search.maven.org/artifact/com.graphql-java/graphql-spring-boot-starter/5.0.2/jar, which is deprecated already.

**Comment by LeslieMurphy** [comment]
Thank you!  

Would you mind explaining to me what the difference is between the kickstarter and the other version?

I was using 
com.graphql-java:graphql-spring-boot-starter v5.0.2
com.graphql-java:graphql-java-tools v 5.2.4

That worked fine for built-in scalars, but is incompatible with graphql-java-datetime

When I switched to this, it worked including the new scalar types  :-)

com.graphql-java-kickstart:graphql-spring-boot-starter  v7.0.1
com.graphql-java-kickstart:graphql-java-tools  v6.0.2
com.zhokhov.graphql:graphql-datetime-spring-boot-starter v2.0.0

Also if you don't mind - is there a trick in the Maven repository to link over to the change log to see what is new in each release?

Thanks again!

**Comment by donbeave** [comment]
In this particular case only by following this project on Github and sometimes check their documentation, just because they have changed the package name. For the Gradle project, you can use this plugin: https://github.com/ben-manes/gradle-versions-plugin.

Here is an example how to use it:
https://github.com/donbeave/graphql-java-datetime/blob/master/check-dependency-updates.sh
https://github.com/donbeave/graphql-java-datetime/blob/master/build.gradle

**Comment by donbeave** [comment]
I'll close this ticket, it seems the problem already fixed.
