### ISSUE TITLE
Version 2.1.0 maven repository

### ISSUE THREAD

**Issue by CedMonchicourt** [donbeave/graphql-java-datetime#27]
Hello,

Thank you for the amazing work on this library.
But why version 2.1.0 is not available on the maven repository ?

Thanks,

**Comment by donbeave** [comment]
Hi, @CedMonchicourt !

Seems my Gradle config was broken by me: https://travis-ci.org/github/donbeave/graphql-java-datetime/builds/695757468

I'll fix it today and re-upload it again.

Thank you! Nice catch!

**Comment by donbeave** [comment]
Available now: https://search.maven.org/artifact/com.zhokhov.graphql/graphql-java-datetime/2.1.0/jar
