### ISSUE TITLE
dependencies are omitted for conflict

### ISSUE THREAD

**Issue by rolandkozma** [donbeave/graphql-java-datetime#3]
Hi,
 First of all, nice work with this library! 
In my project I'm using graphql-spring-boot-starter with graphql-java-tools, but unfortunately I'm not able to use your library.
After I configured my settings to get the dependency from jcenter.bintray.com, It gave me some errors saying that some dependencies are omitted for conflict - I attached the screen-shot.

Building from the command line says:
[WARNING] The POM for com.graphql-java:graphql-java:jar:2017-07-11T00-52-23 is missing, no dependency information available
Which is in conflict with version 4.1.2 as you can see in screenshot.

In my pom I have:
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>3.9.2</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>4.1.2</version>
        </dependency>

Thanks,
- Roland

![graphql-datetime](https://user-images.githubusercontent.com/5465435/31225216-bc37122e-a9d9-11e7-8274-51c9649ba75e.png)

**Comment by donbeave** [comment]
Hi, Roland!

Thanks for the report, I will upgrade this library to use latest release versions, instead of using snapshots.

Best regards,
  Alexey Zhokhov.

**Comment by rolandkozma** [comment]
The only concern I have is that I won't be able to upgrade to new graphql-java-tools / graphql-spring-boot-starter releases in the future because graphql-java-datetime will depend on older versions and again, conflicts will occur in classpath. 
It would be great to do it somehow to detect the versions of these dependencies from my project's pom.xml.

**Comment by PandaMonkey** [comment]
Hi @rolandkozma , Could you show your pom file? I am interested in such version conflict problems. Maybe I can help you identify the root cause. If you concern the privacy problem, you can also send it to my e-mail: pandamonkey1@sina.com

**Comment by rolandkozma** [comment]
I decided to not use this library. It was useful anyway and I reviewed the implementation. Then I added the required configs & code to the project myself.
