### ISSUE TITLE
Bug in Duration bean (GraphQLDateTimeAutoConfiguration)

### ISSUE THREAD

**Issue by setchy** [donbeave/graphql-java-datetime#30]
In GraphQLDateTimeAutoConfiguration.java, the Duration bean has a bug/typo.

It is getting the OffsetDateTime scalarName configuration property, rather than its own Duration scalarName.

**Comment by setchy** [comment]
PR sent #31

**Comment by donbeave** [comment]
@setchy again, thank you for this fix! Already merged, I'll release it with a 2.3.1 version today.

**Comment by setchy** [comment]
Perfect, thanks @donbeave

**Comment by donbeave** [comment]
@setchy released: https://bintray.com/donbeave/maven/graphql-java-datetime/2.3.1. I think tomorrow will be available in the Maven Central repository.
