### ISSUE TITLE
Issue for 3.1.0 autoconfigure dependencies

### ISSUE THREAD

**Issue by setchy** [donbeave/graphql-java-datetime#38]
Was scratching my head for a little bit until I realized that there is a incorrect Version property in graphql-datetime-autoconfigure

It is using Versions.springBoot when it indeed should be Versions.graphQlSpringBoot

This is causing transitive dependency issues for my maven builds

**Comment by donbeave** [comment]
@setchy thank you! Will fix it now. Sorry for this.

**Comment by setchy** [comment]
Thanks @donbeave - do you think you'll release a hotfix?

**Comment by donbeave** [comment]
Released: https://bintray.com/donbeave/maven/graphql-java-datetime/4.0.0
