### ISSUE TITLE
Update graphql-kickstart to v12

### ISSUE THREAD

**Issue by oliemansm** [donbeave/graphql-java-datetime#40]
GraphQL kickstart is getting a major module and package overhaul which means it'll cause breaking changes here too. Most likely the `GraphQLJavaToolsAutoConfiguration` will have to be updated as well. See also https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/617.

**Comment by oliemansm** [comment]
@donbeave i still have to fix some failing tests, and I'll release a 11.1.0 version first before merging that draft PR. So make sure to verify that PR has been merged and 12.0 snapshot is available before starting work. This was more of a heads up so you know it's coming 😃

**Comment by setchy** [comment]
`graphql-java` 17.0 was released this morning.  

Seems like a good opportunity to combine releasing `graphql-spring-boot` 12.0 and an updated `graphql-java-datetime` that addresses the above

**Comment by donbeave** [comment]
@setchy agree!

@oliemansm do you plan to upgrade `graphql-java` dependency in `graphql-spring-boot` module?

**Comment by donbeave** [comment]
Can try the latest snapshot `4.1.0-SNAPSHOT`, which uses `graphql-spring-boot` 12.0.0-SNAPSHOT and `graphql-java` 17.1.

**Comment by oliemansm** [comment]
@donbeave I release 12.0.0 yesterday with graphql-java 17.3 support

**Comment by donbeave** [comment]
@setchy @oliemansm I have released `4.1.0` version of `graphql-java-datetime` yesterday as well. All dependencies upgraded to the latest versions.

Please check it here:
https://search.maven.org/artifact/com.zhokhov.graphql/graphql-java-datetime/4.1.0/jar

**Comment by oliemansm** [comment]
@donbeave Great, thanks!
