### ISSUE TITLE
Make type name configurable

### ISSUE THREAD

**Issue by lestard** [donbeave/graphql-java-datetime#5]
I have a GraphQL Schema that I don't like to change. It defines a scalar type "DateTime". It matches to your "GraphQLLocalDateTime", however, in your implementation the name "LocalDateTime" is used and therefore GraphQL-Java is complaining.

Can we make the name of the type configurable? A possible solution would be to add a second constructor that accepts the "name" argument (and maybe also the description?) and reuses the Coercing that you have created. At least in my use-case this would solve my problem. Would you accept such a pull-request?
Is there any other solution?

Thanks a lot

**Comment by donbeave** [comment]
I'm okey to make it configurable. Like you can define it in "application.yml" which type you prefer to use. If you can do a PR, it can help me to save some time.

**Comment by donbeave** [comment]
@lestard pls check this PR https://github.com/donbeave/graphql-java-datetime/pull/6

**Comment by lestard** [comment]
Sorry that I wasn't responding. The PR #6 looks great and is exactly what I was wishing for in this issue.

**Comment by donbeave** [comment]
Ok, great! Then I'll close this issue.
