### ISSUE TITLE
Add property to convert between UTC and default ZoneId

### ISSUE THREAD

**Issue by oliemansm** [donbeave/graphql-java-datetime#9]
The `DateTimeHelper` uses `ZoneOffset.UTC` for serializing and deserializing dates. The problem in our apps is that the `LocalDateTime` uses a different zone than UTC by default. So `ZoneId.systemDefault()` is equal to Amsterdam in our case. 

It would be nice if we could enable a property to have the `DateTimeHelper` automatically convert between UTC and the `ZoneId.systemDefault()`. Default behavior would stay as is to not break the lib for anybody else using it.

**Comment by donbeave** [comment]
@oliemansm, I’m ok to provide ability to change this behaviour through application.yml. Can you make a PR?

**Comment by oliemansm** [comment]
@donbeave Yeah, I'll take a look.

**Comment by donbeave** [comment]
@oliemansm, awesome!
